- name: RoboShop Setup
  hosts: all
  become: yes
  roles:
    - "{{ROLE_NAME}}"

#  ansible-playbook -i frontend-dev.rajdevops.online, roboshop.yml -e HOSTS=all -e ROLE_NAME=frontend -e ansible_user=centos -e ansible_password=DevOps321
#  ansible-playbook -i catalogue-dev.rajdevops.online, roboshop.yml -e HOSTS=all -e ROLE_NAME=catalogue -e ansible_user=centos -e ansible_password=DevOps321