- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

# Commented for DOC DB
#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.rajdevops.online
#    file: "/app/schema/{{component}}.js"
#    idempotent: yes

# Added for DOC DB to connect from app
- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-cmscnppwjzuf.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_USER", region='us-east-1' ) }} --password {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_PASS", region='us-east-1' ) }} < /app/schema/{{component}}.js

