- name: Install Python Deps
  ansible.builtin.yum:
    name:
      - python3-PyMySQL
      - mysql
    state: installed

# Commented to add terraform rds configuration

#- name: Load MySQL Schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/schema/{{component}}.sql
#    login_host: mysql-dev.rajdevops.online
#    login_user: root
#    login_password: "{{ root_mysql_password }}"
#  vars:
#    root_mysql_password: "{{ lookup('aws_ssm', '{{env}}.mysql.DB_ADMIN_PASS', region='us-east-1' ) }}"


- name: Check Schema is Loaded or not
  community.mysql.mysql_info:
    filter:
      - databases
    exclude_fields: db_size
    return_empty_dbs: false
    login_host: "{{ lookup('aws_ssm', '{{env}}.rds.ENDPOINT', region='us-east-1' ) }}"
    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1' ) }}"
    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1' ) }}"
  register: out

- name: print out
  debug:
    msg: "{{out}}"

# Load only if schema is not yet loaded
# RDS created using terraform
- name: Load MySQL Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: "{{ lookup('aws_ssm', '{{env}}.rds.ENDPOINT', region='us-east-1' ) }}"
    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1' ) }}"
    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1' ) }}"
  when: "'cities' not in out.databases"