route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "raj479.mits@gmail.com"
        from: "raj479.mits@gmail.com"
        smarthost: "ses-smtp-user.20230129-233547:587"
        auth_username: "{{ lookup('aws_ssm', 'ses.user', region='us-east-1' ) }}"
        auth_password: "{{ lookup('aws_ssm', 'ses.pass', region='us-east-1' ) }}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
